# Generated by Django 4.2.2 on 2023-07-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriber_rename_usersubscription_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
