# Generated by Django 4.2.2 on 2023-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_event_subscription_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
