# Generated by Django 4.2.2 on 2023-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriber_name_subscriber_subscribed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
