# Generated by Django 4.2.2 on 2023-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscriber_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
