# Generated by Django 4.2.2 on 2023-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_subscriber_name_subscriber_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
