# Generated by Django 4.2.2 on 2023-08-01 06:33

from django.db import migrations, models
from django.utils.crypto import get_random_string

def generate_random_activation_code(apps, schema_editor):
    Subscriber = apps.get_model('users', 'Subscriber')
    for subscriber in Subscriber.objects.all():
        subscriber.activation_code = get_random_string(length=100)
        subscriber.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_subscriber_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='activation_code',
            field=models.CharField(max_length=100, null=True),  # Nullable during the migration
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(generate_random_activation_code),
        migrations.AlterField(
            model_name='subscriber',
            name='activation_code',
            field=models.CharField(max_length=100),  # Removing the NULL constraint after populating
        ),
    ]
