# Generated by Django 4.2.2 on 2023-08-01 06:37

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subscriber_activation_code_subscriber_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='activation_code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=100, unique=True),
        ),
    ]
