# Generated by Django 4.2.2 on 2023-08-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_subscriber_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='activation_code',
            field=models.CharField(default='0VscHTxRYsJ8b2HHNJOiI9NX4W3yyxKw', max_length=100, unique=True),
        ),
    ]
