# Generated by Django 4.2.2 on 2023-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_subscriber_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='activation_code',
        ),
    ]
