# Generated by Django 4.2.2 on 2025-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_subscriber_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
