# Generated by Django 4.2.2 on 2025-02-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_subscription_firstname_subscription_lastname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
