# Generated by Django 4.2.2 on 2025-03-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_delete_subscriber_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriber_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
