# Generated by Django 4.2.2 on 2025-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriber_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
