# Generated by Django 4.2.2 on 2025-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscriber_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
