# Generated by Django 4.2.2 on 2025-02-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_event_subscriber_activation_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
