# Generated by Django 4.2.2 on 2025-02-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscriber_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
