# Generated by Django 4.2.2 on 2025-03-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscriber_subscribed_at_subscription_subscribed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed_at',
        ),
    ]
